# SPDX-License-Identifier: MIT
#
# Math helpers extracted from Nitro Engine's md5_to_dsma tool. Keeping these
# identical to the original tool guarantees that the DSM/DSA files generated by
# this add-on are byte-compatible with the ones produced by md5_to_dsma.py.

from collections import namedtuple
from math import sqrt

# Intermediate data model. It mirrors exactly what md5_to_dsma builds after
# parsing a .md5mesh / .md5anim file, so the same conversion code can run on it.
Joint = namedtuple("Joint", "name parent pos orient")
Vert = namedtuple("Vert", "st startWeight countWeight")
Weight = namedtuple("Weight", "joint bias pos")
Mesh = namedtuple("Mesh", "numverts verts numtris tris numweights weights")


class Quaternion():
    def __init__(self, w, x, y, z):
        self.w = w
        self.x = x
        self.y = y
        self.z = z

    def to_v3(self):
        return Vector(self.x, self.y, self.z)

    def complement(self):
        return Quaternion(self.w, -self.x, -self.y, -self.z)

    def normalize(self):
        mag = sqrt((self.w ** 2) + (self.x ** 2) + (self.y ** 2) + (self.z ** 2))
        return Quaternion(self.w / mag, self.x / mag, self.y / mag, self.z / mag)

    def mul(self, other):
        w = (self.w * other.w) - (self.x * other.x) - (self.y * other.y) - (self.z * other.z)
        x = (self.x * other.w) + (self.w * other.x) + (self.y * other.z) - (self.z * other.y)
        y = (self.y * other.w) + (self.w * other.y) + (self.z * other.x) - (self.x * other.z)
        z = (self.z * other.w) + (self.w * other.z) + (self.x * other.y) - (self.y * other.x)
        return Quaternion(w, x, y, z)


class Vector():
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def to_q(self):
        return Quaternion(0, self.x, self.y, self.z)

    def length(self):
        return sqrt((self.x ** 2) + (self.y ** 2) + (self.z ** 2))

    def normalize(self):
        mag = self.length()
        return Vector(self.x / mag, self.y / mag, self.z / mag)

    def add(self, other):
        return Vector(self.x + other.x, self.y + other.y, self.z + other.z)

    def sub(self, other):
        return Vector(self.x - other.x, self.y - other.y, self.z - other.z)

    def cross(self, other):
        x = (self.y * other.z) - (other.y * self.z)
        y = (self.z * other.x) - (other.z * self.x)
        z = (self.x * other.y) - (other.x * self.y)
        return Vector(x, y, z)

    def mul_m4x3(self, m):
        x = (self.x * m[0][0]) + (self.y * m[0][1]) + (self.z * m[0][2]) + (m[0][3] * 1)
        y = (self.x * m[1][0]) + (self.y * m[1][1]) + (self.z * m[1][2]) + (m[1][3] * 1)
        z = (self.x * m[2][0]) + (self.y * m[2][1]) + (self.z * m[2][2]) + (m[2][3] * 1)
        return Vector(x, y, z)


def joint_info_to_m4x3(q, trans):
    """
    This generates a 4x3 matrix that represents a rotation and a translation.
    q is a Quaternion with an orientation, trans is a Vector with a translation.
    """
    wx = 2 * q.w * q.x
    wy = 2 * q.w * q.y
    wz = 2 * q.w * q.z
    x2 = 2 * q.x * q.x
    xy = 2 * q.x * q.y
    xz = 2 * q.x * q.z
    y2 = 2 * q.y * q.y
    yz = 2 * q.y * q.z
    z2 = 2 * q.z * q.z

    return [[1 - y2 - z2,     xy - wz,     xz + wy, trans.x],
            [    xy + wz, 1 - x2 - z2,     yz - wx, trans.y],
            [    xz - wy,     yz + wx, 1 - x2 - y2, trans.z]]


def world_to_joint_space(point, joint_pos, joint_orient):
    """
    Express a point given in the same space as the joints in the local space of
    a joint. This is the inverse of the transform used at runtime:

        world = joint_pos + joint_orient * local * conj(joint_orient)

    so the inverse is:

        local = conj(joint_orient) * (world - joint_pos) * joint_orient
    """
    q = joint_orient
    qt = q.complement()
    rel = point.sub(joint_pos).to_q()
    return qt.mul(rel).mul(q).to_v3()
